### ISSUE TITLE
Lights not showing

### ISSUE THREAD

**Issue by quentin-roche** [adizanni/floor3d-card#63] opened 2021-11-21 21:51 UTC
Hello, thank you for this amazing project!

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

1.1.15

**Browser and Operating System:**
 
Android Chrome: 96.0.4664.45
Android home assistant companion app: 2021.10.0-full
IOS Chrome: 96.0.4664.53
IOS home assistant companion app: 2021.11.1-full

**Description of problem:**

On iOS and Android lights are not showing (chrome and Companion app). It works perfectly on chrome on Windows.

I tried removing lights and disabling shadows. Nothing seems to work

**Javascript errors shown in the web inspector (if applicable):**

No JS error

**Additional information:**

You can find my model / config here:
https://synology.roche-collet.family/d/s/mMCvHSY5vyL7zfoiv90jMRX5JwQBx92i/fAJntw1X_StiZN_UI2IZpv6Z7ZlwnTHs-sLHguCO9FQk

**Comment by adizanni** [comment] 2021-11-22 22:12
Bonjour  Quentin,

I have loaded your model in my Home Assistant and I  have bound only one light. The model is working in both  Android and iOS (with Chrome, Firefox and companion app).
I've also checked your yaml that seems correct, of course I've not tried to put a light in each of your light objects but it does not seem this would cause any issue. Please try to add one light at a time and check if there is one of the object that is causing problems in mobile. 
I've obly experienced issue when loading models with more than the allowed lights and shadow activated. I understand you have tried all combinations but I'm really unable to reporduce your issue.

Andrea.

**Comment by adizanni** [comment] 2021-12-02 06:19
@quentin-roche , this has been opened for a while without any feedback, if no answer by next Saturday I will close the issue as I cannot reproduce it

**Closed** 2021-12-04 09:42 UTC
Labels: bug
