### ISSUE TITLE
ENTITIES LIST INCOMPLETE

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#86] opened 2022-03-02 21:03 UTC
GOOGLE CHROME 
Version 98.0.4758.102  64 bits

**Description of problem:**
ERRORS FOUND

1) In the "Type and Object" list, only 2 options appear to be configured:
-Entity_Template:
-Object:

2) In the Entity_Template field, the filling options must be entered manually (light, color, etc...), as they do not work with the double click;

3) After filling in the fields (Entity, Entity_Template and Object) and selecting the SAVE option, the card crashes and is deleted from the interface, not allowing the option "ADD NEW CARD" to be selected again for this page

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

![ENTITY TEMPLATE1](https://user-images.githubusercontent.com/73760504/156449260-c944b83c-982e-42e6-8846-a6b0fb4b15ab.jpg)
![ENTITY TEMPLATE2](https://user-images.githubusercontent.com/73760504/156449273-fe2b0669-bc30-414f-9513-ab81125985b7.jpg)
![ENTITY TEMPLATE3](https://user-images.githubusercontent.com/73760504/156449283-3898de15-1ccd-4a19-a4f2-1130d7980e76.jpg)

![ENTITY TEMPLATE4](https://user-images.githubusercontent.com/73760504/156449290-f0036800-00c1-4f20-acb7-2a6adaf7f0f6.jpg)

**Comment by adizanni** [comment] 2022-03-02 21:13
Hello @VITCHEPF, I do not get your problem. The Entity Template should be used to transform the value of the state of the entity and is using the Javascript notation: [[[ javascript instructions ]]] and you use the $entity macro to refer the state value. Example: [[[ ($entity > 20) ? 'hot' : 'cold' ]]] and then you can use the template value in a Text, Hide, Show, Color 3d type. Tell me if it is clear.
Also when the problem with the card crash happen you can solve it by using the "raw configuration editor" in the upper right corner

**Comment by VITCHEPF** [comment] 2022-03-02 21:24
Hi adizzani. According to your video we should have more options to be configured in the card.
I cannot see these options in my card (ser attached picture)

![Screenshot_20220302-181852](https://user-images.githubusercontent.com/73760504/156452055-8a93d94e-f1e3-4f2e-89db-e32c237a25d8.jpg)

**Comment by VITCHEPF** [comment] 2022-03-02 21:27
I have only "entitiy template" and "object', and the card crashes after be filled.

**Comment by adizanni** [comment] 2022-03-02 21:36
The options are appearing when you select the type of the entity with the type3d list box.
You just click on the type section to expand and see all parameters

**Comment by adizanni** [comment] 2022-03-02 21:44
You have to expand the light section with the arrow at the right of the light label

**Comment by VITCHEPF** [comment] 2022-03-03 02:15
It's probably a problem with the Javascript Module, which is not opening the Options menu correctly and filling  with texts that make no sense. See the sequence of images below:


![ENTITY TEMPLATE](https://user-images.githubusercontent.com/73760504/156483139-29ea4acb-f1c9-41ad-aad7-9ba6eb5b90aa.jpg)



![ENTITY TEMPLATE1](https://user-images.githubusercontent.com/73760504/156483156-924f41f5-74dc-477f-9ec1-12def24d22b8.jpg)

**Comment by VITCHEPF** [comment] 2022-03-03 02:19
The light label also don't appear in my menu.

**Comment by adizanni** [comment] 2022-03-03 06:11
Please open the web console. In chrome it is under "more tools" "web developer tools" and copy paste the content here if you see errors. I've never seen that problem!

**Comment by adizanni** [comment] 2022-03-03 08:28
Maybe it is related to a wrong management of a character set, please paste your log here while the config editor is open

**Comment by VITCHEPF** [comment] 2022-03-03 14:24
Ciao @ADIZANNI, please see if the information below can help you to find the error:



![TELA1](https://user-images.githubusercontent.com/73760504/156582082-09dad55e-58c8-458f-afec-6c21bf6b20c2.jpg)

**Comment by VITCHEPF** [comment] 2022-03-04 00:27
When I open de "web developer tools" these are the error codes that appear:

1) The errors are relative to other repositories I have installed on HA:

![ERRO LIST](https://user-images.githubusercontent.com/73760504/156673216-7df14dac-da29-4985-b073-9a4ea29581da.jpg)


2) At the end of Floor3DCard this error appears:



![ERRO LIST 2](https://user-images.githubusercontent.com/73760504/156675831-a9695d87-dfbb-4a41-b165-a06fb17d2919.jpg)

**Comment by VITCHEPF** [comment] 2022-03-04 12:13
Hi @adizanni,   

I believe I have found the problem of not showing the two dropdown menus (Action and 3D Type), in Chrome and Edge Browser. In both browsers the element "paper-dropdown menu" doesn't display the dropdown menu, and the list items do not appear as a stylized "menu", but just a list of items that appear on the page.

The problem is in the rendering of this component in the  browsers above.
Do you have any solution or suggestion for this problem?

If you search on the internet you will find many cases that had a problem with this component.

- Maybe change tho other element in the next revision

**Comment by VITCHEPF** [comment] 2022-03-04 16:29
Sorry, I didn't understand what config yaml file are you talking. Is It the HA configuratiom.yaml?

**Comment by VITCHEPF** [comment] 2022-03-04 17:33
Hi see below the code:

type: custom:floor3d-card
entities:
  - entity: light.sala_smart_b1
    object_id: Cama_Casal_1
object_groups:
  - object_group: ''
name: CASA DA SERRA
path: /local/casa_serra_3d/
objfile: home.obj?ver=1
mtlfile: home.mtl?ver=1
style: 'width: 900px; height: 640px'
globalLightPower: '1'
backgroundColor: black
camera_position:
  x: 23.959384963783954
  'y': 1869.702394193341
  z: 995.0504655083691
camera_rotate:
  x: -1.1096502872822176
  'y': -0.01654519544897422
  z: -0.03328456049705004
camera_target:
  x: 58.91694357752425
  'y': -22.275539658639808
  z: 54.970263154604964
shadow: 'no'

If I include manually the line in Bold below, because I don't have the interface to input this data, the card stop to work and crashes:

entities:
  - entity: light.sala_smart_b1
    object_id: Cama_Casal_1
    **type3d: light**

**Comment by VITCHEPF** [comment] 2022-03-04 23:59
Additional information: the problem is not related to the Operating System. because I tested on Windows 10 Home, Windows 10 Pro and Android 9 and they all have the same error.

**Comment by adizanni** [comment] 2022-03-05 09:02
Have you tried to start from a blank card ? I do not see anything wrong with your configuration. Unfortunately I cannot reproduce the issue in my environment and I have not received other feedback, neither here nor in the forum. Today I have a bit more time so I will try to dig

**Comment by VITCHEPF** [comment] 2022-03-05 14:01
Now I started with a new Panel, Blank Card and New Page, but unfortunatelly the error still the same:
![ERRO](https://user-images.githubusercontent.com/73760504/156886599-ff5990a0-c911-4cdd-b5e3-0e8a63ba906b.jpg)

**Comment by VITCHEPF** [comment] 2022-03-05 14:21
As I told you before, I prove to type manually the proprieties below (Bold), but after include this lines the rrendering stops working and the card freeze:


type: custom:floor3d-card
entities:
  - entity: light.sala_smart_b1
    object_id: Cama_Casal_1
    **type3d: light
    light:
      lumens: '900'
      shadow: 'yes'
      angle: '0'**

![ERRO](https://user-images.githubusercontent.com/73760504/156887353-86a4c39c-b900-4490-953c-b6e6d4244cc4.jpg)

**Comment by VITCHEPF** [comment] 2022-03-05 14:27
To make the page and the card open again, I need to open the Raw Editor and delete the included lines manually

**Comment by adizanni** [comment] 2022-03-05 15:47
Please put always the log in the console as you did before.
Try to start with a simple model you download from the samples in SweetHome3d (no levels, no fancy objects, no plugin. etc).
If everything is working including the editor and the possibility to add lights,  switch to your model.
Start from an empty card: do not add any lights and tell me if the model is displayed and the console is not showing any issue.
Start by adding the light in the editor and show me the console error (if any).
If the visual editor is always having the same problem with the dropdown lists, switch to the code editor.
In your config above:  remove the angle: it is only useful when you also put target object or target direction which is not the case for you; but it should not hurt.
A light requires only the entity, the object_id the type (light), the light section and the lumens to work
It is difficult to debug if I do not understand why you have a problem with the editor, I have not been reported of this problem from anybody else and I cannot reproduce it in my environment

**Comment by VITCHEPF** [comment] 2022-03-05 19:05
STEP 1: New Panel and New Card empty created

![ERRO0](https://user-images.githubusercontent.com/73760504/156895953-c493b845-d3e3-4448-baf4-4eed19a2cc27.jpg)



STEP 2: Open the Floor3d Card --> Entity --> Type and Object
The paper-dropdown menu Action and the paper-dropdown menu 3D Type do not appear.

![ERRO](https://user-images.githubusercontent.com/73760504/156896095-c376a617-31aa-4284-8afe-5bb6701f57f9.jpg)


STEP 3: Loading a Basic 3D Model justo to check what happens

![ERRO1](https://user-images.githubusercontent.com/73760504/156896385-1f964c42-6463-4745-bdca-72499415cdad.jpg)

In my opinion, not showing the 3D Type paper-dropdown menu object is not related to incorrectly typed or created code, but to some incompatibility between the paper-dropdown menu object and my Home Assistant in Portuguese (BR) - maybe.
Do you have contact with any other users in Brazil who are using this card?

It seems that this object is not being created in memory, because in addition to not appearing in the interface, when I try to manually assign a value to it, the 3d card crashes

**Comment by VITCHEPF** [comment] 2022-03-05 19:13
Would  be possible for you to generate a new code, just for my test, changing the objects "paper-dropdown menu Action" and "paper-dropdown menu 3D Type" by another input object?

So I could test if the interface will load correctly or if there is some other incompatibility problem with my system.

**Comment by adizanni** [comment] 2022-03-05 22:36
I'm loading a new official version where I have replaced the paper-dropdown with the ha-paper-dropdown which is the one used in lovelace. I've done some test to be sure I'm not breaking things that work in my environment, hope that this can fix the issue in your environment. the new release with the fix will be 1.3.4. If this is not working I will ask you to create an input_select entity so that you can test the behaviour of the ha-dropdown in the standard gui of Home Assistant...

**Comment by VITCHEPF** [comment] 2022-03-05 23:11
Can you please compare my generated code with your generated code, for the component  "paper-dropdown menu Action", to see if there are differences?

I Splitted in 3 parts

**1) Complete Routine "paper-dropdown menu Action"** 

![DROP1](https://user-images.githubusercontent.com/73760504/156902654-f2a9b239-3ea7-4adb-ba86-fa3dcef32b68.jpg)


**2) PICTURE 2**
![DROP2](https://user-images.githubusercontent.com/73760504/156902666-5e5a803a-f3b8-4071-9fdd-690bbff96d9f.jpg)



**3) PICTURE 3**

![DROP3](https://user-images.githubusercontent.com/73760504/156902668-50cacb7b-5a98-446e-9643-c0672908dc12.jpg)




================================================================================
I'm suggesting to compare, because I found some links on the internet that indicate a possible error in the construction of the code

https://stackoverflow.com/questions/27299934/paper-dropdown-menu-default-selected-option-doesnt-work

**Comment by VITCHEPF** [comment] 2022-03-06 02:34
**Release 1.3.4 and HA Input Select Test:**


![DROP1](https://user-images.githubusercontent.com/73760504/156906709-0a495a73-7b28-4554-8118-e06a7c68c4ce.jpg)



![DROP2](https://user-images.githubusercontent.com/73760504/156906726-dc19849f-09b3-436d-b7b0-f6220f984c66.jpg)

**Comment by VITCHEPF** [comment] 2022-03-06 04:10
Starting with a new 3D card

![ERRO](https://user-images.githubusercontent.com/73760504/156908855-ccec335e-76ba-4027-a9a1-5f2a12702c26.jpg)

**Comment by adizanni** [comment] 2022-03-06 09:42
Please send me the html generated for the input_select and the code generated for the type3d field. Please do not create picture snapshot; you can copy paste the full element tree from the developers tool and paste them here or in a file if they are too big and you can share the file via file drop cloud service....

**Comment by adizanni** [comment] 2022-03-07 16:20
Also please try to do a test with this card editor it is using the same contols as me (I got the majority of the editor code from it).
https://github.com/custom-cards/bar-card

**Comment by adizanni** [comment] 2022-03-07 17:40
Another question: have you upgraded HA to 2022.3.x ?

**Comment by adizanni** [comment] 2022-03-07 18:57
Hello @VITCHEPF as it finally turned out, you discovered an important issue that appears after upgrade to 2022.3 (which is not yet the case for me). I'm working to quickly switch to MWC elements, I will post a new release when ready. The patches I've posted in beta are not working.....

**Comment by VITCHEPF** [comment] 2022-03-07 20:14
Thanks for the feedback. I'am look forward to the new version.

**Comment by VITCHEPF** [comment] 2022-03-07 20:39
I see that:
https://developers.home-assistant.io/blog/2022/02/18/paper-elements/

**Comment by adizanni** [comment] 2022-03-07 21:58
It is not a minor change and it was announced without giving it the right importance

**Comment by VITCHEPF** [comment] 2022-03-08 12:11
Hi, did you solve the problem in the version 1.3.5?
I uploaded and for me the problem still the same:
![ERRO](https://user-images.githubusercontent.com/73760504/157235758-190f2422-52b6-40c8-998d-424d6cf63191.jpg)

**Comment by adizanni** [comment] 2022-03-08 12:19
Hello @VITCHEPF release 1.3.5-HF1 is out with the paper elements fix (I did a wrong release right before). Please verify if it is working for you and thanks again for your resiliency in supporting your case, otherwise

**Comment by adizanni** [comment] 2022-03-08 12:50
Still down! I apologize. Need to rollback release

**Comment by VITCHEPF** [comment] 2022-03-09 16:39
Hi, Sorry but I didn't understand If the actual version available 1.3.4 it's the final version with the paper elements fixed or not?

**Comment by adizanni** [comment] 2022-03-09 16:43
If you moved to HA 2022.3 there is no version fixing the issue for the moment (i'm working at it), it is anyway better to revert to 1.3.4 because all 1.3.5.x were deleted

**Comment by adizanni** [comment] 2022-03-09 20:11
v1.3.6 is out there to fix the issue, please give me feedback and thanks for the patience......

**Comment by VITCHEPF** [comment] 2022-03-09 20:58
Congratulations! You solved the biggest problem.

Now it's minor adjustments:

See below:

![ERRO](https://user-images.githubusercontent.com/73760504/157534543-c59b63da-2b72-4b8a-a07b-03728460ca1b.jpg)





![ERRO1](https://user-images.githubusercontent.com/73760504/157534569-fd3c6589-c992-432d-9035-a53d2a707459.jpg)



![ERRO2](https://user-images.githubusercontent.com/73760504/157534593-2b365e89-37d0-4fa6-bdd5-926a0c1507ad.jpg)

**Comment by VITCHEPF** [comment] 2022-03-09 21:02
Additionally
![ERRO3](https://user-images.githubusercontent.com/73760504/157535445-9e605204-431f-41b3-b7d4-e407b460ee94.jpg)

**Comment by adizanni** [comment] 2022-03-09 22:39
the bracket around the option means it is the default selection.

**Comment by adizanni** [comment] 2022-03-09 22:40
For everybody's reference, if you are looking for the solution to the paper element issue introduced by HA 2022.3, I found this repository (https://github.com/piitaya/lovelace-mushroom) gives the most elegant solution.

**Comment by VITCHEPF** [comment] 2022-03-12 02:06
I adizanni, just as feedback.
I did today some tests with the last release and it seems that the main functions are ok

I will be in touch to let you know if anything strange happens.

Tks
![TESTE](https://user-images.githubusercontent.com/73760504/157999614-8ae4a6df-bcfe-486d-9344-de9d8921c634.jpg)

**Comment by VITCHEPF** [comment] 2022-03-12 02:24
I remember seeing something like a "double click" on the object to turn the lamp on and off. 
Am I right? 
What do I need to configure this?

**Comment by adizanni** [comment] 2022-03-12 10:51
Hello @VITCHEPF for discussion it is better to use the forum, you can also send me direct messages. There is nothing to configure for the double click. By default if you double click on the object associated to the light, it should turn on and off the light, if you want to double-click on another object to turn on the light (ex a switch) you have to use the 3d type called "gesture". 
I think I have solved the issue with the menu (at least for the 3d type field); give me feedback and then we can close the issue.

**Closed** 2022-03-12 15:21 UTC
Labels: bug, question
