### ISSUE TITLE
Light switches on, but it the image is showing light in a wrong place

### ISSUE THREAD

**Issue by chrisvor** [adizanni/floor3d-card#52] opened 2021-09-01 07:38 UTC
**Description of problem:**

I have managed to export my sweethome3d plan into obj's and successfully installed it in HA. The house shows perfectly on the card and I can turn it around and zoom in/out just fine.

However, when I double-click on a light, the correct light switches on, but the display shows a wrong room as lit by the light.

For example, I double click on the ceiling-light in th emiddle of the image:
![image](https://user-images.githubusercontent.com/2786551/131632008-ec5f22cb-0fd0-452a-9c71-270cb57d2141.png)

The room on the LEFT of the room the light is in, is lit up.
![image](https://user-images.githubusercontent.com/2786551/131631738-c9cc2ff0-7196-4885-857c-0fd0626d7239.png)

**Additional information:**

**Comment by adizanni** [comment] 2021-09-02 10:59
Hello Chris, are you using the ExportToHASS plugin ? If yes have you verified that lights have different names in the SH3D model ?
If not I have to investigate why, you should send your obj file for me to verify

**Comment by adizanni** [comment] 2021-09-07 21:42
Hey Chris, I cannot reporoduce your problem. can you please provide more info ? The model for instance...

**Comment by adizanni** [comment] 2021-09-12 18:26
Hello Chris, in the absence of other answers I close this bug as I cannot reproduce it

**Closed by adizanni** 2021-09-12 18:26 UTC
Labels: bug
