### ISSUE TITLE
"Door" are not function correct

### ISSUE THREAD

**Issue by smekac95** [adizanni/floor3d-card#47] opened 2021-08-28 10:14 UTC
Hello, 
I try to use "door" in 3Dflorplan. If I chose one part of door, is animated only this part, no glass, no holder :-). Issue you can see in image. 

![image](https://user-images.githubusercontent.com/63142185/131214570-1ca0fd78-853b-4ed4-8b8c-aa78eee0520f.png)

**Comment by mcv93us** [comment] 2021-08-28 15:25
For now there is no support for the item group and a door as you have
  highlighted is made up of several objects (frame, handle, glass ...)
They are making tremendous progress with this HA extension and I think they will soon be able to handle animations of groups of objects as well.

**Comment by adizanni** [comment] 2021-08-28 15:28
Hello Smekac, yes this is a know issue. At the moment I can only move one object and the feature dose not work for object_groups. 

There are 2 things:

1. if you are familiar with my sweethome3d plugin (https://github.com/adizanni/ExportToHASS) you can export your model using the plugin. For the door to work as a whole, in Sweet Home 3D, you  just name your door with a sharp (#) in the end (ex DoorLivingRoom#) and it will work like a single object in the Home Assistant card. 
2. If you use the plugin, there is still a collateral effect if the resulting object (including frame and handles) is too thick, when the door opens there is a gap between the  wall and the object (it is due to the algorithm to move the door that is relying on a plane object). I'm working to  a solution for that problem.

**Comment by ikrowni** [comment] 2021-08-28 18:23
> 1. if you are familiar with my sweethome3d plugin (https://github.com/adizanni/ExportToHASS) you can export your model using the plugin. For the door to work as a whole, in Sweet Home 3D, you  just name your door with a sharp (#) in the end (ex DoorLivingRoom#) and it will work like a single object in the Home Assistant card.

This works great with some of the objects in my model but then some of the others end up looking like a wire frame or turn all white and lose all texture/colors. Is there anything i can do to make these objects work properly?

**Comment by adizanni** [comment] 2021-08-28 18:33
Are you sure you have the latest version installed ?

I think I fixed the  texture problem with the help of a contributor a few releases ago.... Send me your model if you have the last version and still does not work as expected

**Comment by uspass** [comment] 2021-08-29 11:06
> 
> 
> Hello Smekac, yes this is a know issue. At the moment I can only move one object and the feature dose not work for object_groups.
> 
> There are 2 things:
> 
>     1. if you are familiar with my sweethome3d plugin (https://github.com/adizanni/ExportToHASS) you can export your model using the plugin. For the door to work as a whole, in Sweet Home 3D, you  just name your door with a sharp (#) in the end (ex DoorLivingRoom#) and it will work like a single object in the Home Assistant card.
> 
>     2. If you use the plugin, there is still a collateral effect if the resulting object (including frame and handles) is too thick, when the door opens there is a gap between the  wall and the object (it is due to the algorithm to move the door that is relying on a plane object). I'm working to  a solution for that problem.

I had the same problem. To solve it I exported the door/window as obj (not ha obj). Then I imported it in Vectary (is a 3d program very easy to use). There I deleted the window/door frame, the hinges and handle and kept only the actual window/door. Back in the SH3D, import the exported from Vectary, and that's it. Oh, and use the # too.

**Comment by adizanni** [comment] 2021-08-29 12:09
Hello uss, thanks for the hint I did exactly the same thing, but it is still a bit complicated and it should be repeated for all window door in the catalog. I'm thinking about a solution that may  work even without the plugin and without a complex transformation. 
But waiting for this solution I think that yours is quite good. By the way for all these obj we create to facilitate the export to the card I thought to build a resource library here https://github.com/adizanni/3DResources

**Comment by smekac95** [comment] 2021-08-30 06:15
Thank all for perfect tips. So looks with it temporarily solved.

**Comment by ikrowni** [comment] 2021-08-30 16:41
> Are you sure you have the latest version installed ?
> 
> I think I fixed the texture problem with the help of a contributor a few releases ago.... Send me your model if you have the last version and still does not work as expected

This is the model if i add # to the end of the name
[female_mannequin.zip](https://github.com/adizanni/floor3d-card/files/7078146/female_mannequin.zip)

and this is without the #
[female_mannequin2.zip](https://github.com/adizanni/floor3d-card/files/7078152/female_mannequin2.zip)


The objects all get grouped together when i use # but on both models the textures dont appear when rendered in home assistant

**Comment by adizanni** [comment] 2021-08-30 16:54
Hello ikrowni, do you have the latest version of the ExportToHASSPlugin also ?

**Comment by ikrowni** [comment] 2021-08-30 21:06
> Hello ikrowni, do you have the latest version of the ExportToHASSPlugin also ?

Just made sure. Yes im on the latest version. 

Heres my full zip made by the plugin
https://drive.google.com/file/d/1CbaAYWmyvqBLxWS5QVMExnIX62jQz-O_/view?usp=sharing

**Comment by uspass** [comment] 2021-08-30 21:17
Did you clear browser cache after rendering?

**Comment by ikrowni** [comment] 2021-08-30 21:26
i did. Ive actually been doing that a lot lately lol

**Comment by adizanni** [comment] 2021-08-30 21:29
Yes you either clear the cache or put a version on the obj and mtl filename (ex home.obj?ver=1 for the first change to the model and 2,3,4 for subsequent changes, the same for the home.mtl?ver=1).

This is showing properly in my home assistant:

![image](https://user-images.githubusercontent.com/35622920/131407593-22bd1f83-0bb7-4fc1-9c29-91d16878bc8e.png)

Just took a small snapshot to show that texture are loaded.

Also please do not activate shadow in the card, I see that you have  a number of lights, this number should not go over the number of available textures that you will find here https://webglreport.com/ (see max texture image unit)

**Comment by ikrowni** [comment] 2021-08-30 21:34
![This is what i see](https://user-images.githubusercontent.com/4442098/131408538-5e4fc55a-0c46-4657-ae60-701008965c09.png)

I dont have shadows activated. i tried that once and everything slowed to a crawl so i turned it off. Ive cleared my cache pretty much every time ive made a change.

**Comment by uspass** [comment] 2021-08-30 21:38
Hi Andy,

It looks ok to me. I see nothing wrong in the rendering of the files he posted

**Comment by adizanni** [comment] 2021-08-30 21:47
Same for me. My color with default ambient light 0.5 are showing a lot brighter.

Now I see the problem, maybe I did not get it in the first rendering:

![image](https://user-images.githubusercontent.com/35622920/131409956-d8078a07-1e5b-45de-b4f0-e1dd8895977f.png)

You mean that the Mannequin should show similar but the woman is appearing without textures, it would be interesting to receive the sh3d file.

**Comment by ikrowni** [comment] 2021-08-30 22:22
[mannequinBrunette.zip](https://github.com/adizanni/floor3d-card/files/7079901/mannequinBrunette.zip)

theres the model.

i have global illumination set to 0.1 thats probably why it looks so dark. thats not the issue im trying to fix though. its the missing textures from my models.

**Comment by ikrowni** [comment] 2021-08-30 22:27
![missing_textures](https://user-images.githubusercontent.com/4442098/131413892-920b5e24-a62f-4f5a-8a1d-7dbee0154d51.png)

I went through and placed a # at the end of every item in my entire model. This was the outcome.

**Comment by uspass** [comment] 2021-08-30 22:40
In home.obj he has a line in the blinds line 14290 ( and a lot more blinds)
l 4270 4271
and also in the shower curtain ( and a lot more courtains) line 42521

**Comment by uspass** [comment] 2021-08-30 22:49
In the manequinBrunette.obj there are 2 lines at the end
l 7974 7976
l 7975 7977

**Comment by ikrowni** [comment] 2021-09-01 18:46
> In the manequinBrunette.obj there are 2 lines at the end
> l 7974 7976
> l 7975 7977

What am i supposed to be doing with these numbers?

**Comment by uspass** [comment] 2021-09-02 12:17
Go to https://3dviewer.net/
Upload manequinBrunette.obj and manequinBrunette.mtl
Press export model.
Export (download) model.obj and model.mtl
Rename to manequinBrunette both.
Do that for all the objects that have line (that is line/s that start with l)
Load objects as furniture in SH3D and change existing objects with new ones you created.
Export HA obj.
That will solve your problems.

Cheers,
us

**Comment by adizanni** [comment] 2021-09-07 21:38
Please try the new release 1.1.0 that is bringing a new management of rotating objects (rotate, doors, windows, etc.).
Let me know if it is easy to understand and if it is woriking according to your expectations

**Comment by adizanni** [comment] 2021-09-09 11:44
@uspass, what about your tests of 1.1.0 ? I know that you opted for managing the door in the model (using the plugin) but did you receive any regression by moving to the new version ?

**Comment by uspass** [comment] 2021-09-10 12:44
@adizanni, except the fact that I had to change some inner to outer and vice-versa (not for all windows), nothing changed. The windows work as supposed.

**Comment by adizanni** [comment] 2021-09-10 14:18
@uspass, sorry for inner outer, I had to take a decision and I decided to revert but in order to fix I would need to define a "inside" object and a "viewer" object. You did already a ExportToHass "magic" but I invite you to test the hinge feature so that you do not need to pass through the Sweethome3d trick. It is working flawlessly and almost all doors and windows in SH3D have hinges

**Comment by adizanni** [comment] 2021-09-10 15:03
@smekac95, what about retesting with the new release

**Comment by uspass** [comment] 2021-09-11 07:54
> 
> 
> @uspass, sorry for inner outer, I had to take a decision and I decided to revert but in order to fix I would need to define a "inside" object and a "viewer" object. You did already a ExportToHass "magic" but I invite you to test the hinge feature so that you do not need to pass through the Sweethome3d trick. It is working flawlessly and almost all doors and windows in SH3D have hinges

@adizanni, no worries.
I will test the hinge stuff, but just for sake of testing.
I don't use hinges and door/window frames because I try to keep the number/size of objects to a minimum.
Now I have 1,500,630 vertex, 2,973,675 triangles and files size altogether 232 MB.
And believe me, I have no unnecessary objects.
It takes 25 seconds to clear cache refresh on my I9 laptop. And this is only for the ground floor :( .

**Comment by uspass** [comment] 2021-09-11 21:30
I did the compare. My approximation with 25 seconds was optimistic.
Floor3D  47 seconds
3DViewer 28 seconds
To make sure the comparison is fair i used files from the HA server to feed 3DViewer.
So yes, there is a significant difference.

**Comment by adizanni** [comment] 2021-09-12 09:31
Ok, you need to consider that there is a post processing after the load that is needed for the card. The more you have entities the more the card needs to add objects. This becomes particularly heavy when shadows are activated.

**Comment by uspass** [comment] 2021-09-12 10:20
I know. But the loading takes 3s +/- 1s for both Floor3D and 3DViewer. The post processing takes the rest.

**Comment by adizanni** [comment] 2021-09-12 18:25
I would like to keep the bug list consistent, I close this bug as it has been managed by v1.1.1, if you see additional issues please log a new ticket.

**Closed by adizanni** 2021-09-12 18:25 UTC
Labels: bug
