### ISSUE TITLE
Objects disappear when using shadow

### ISSUE THREAD

**Issue by Kouwe-sudo** [adizanni/floor3d-card#61] opened 2021-11-08 18:36 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant OS 6.6 : core-2021.11.1**

**Last working release (if known):**

**FireFox on Windows10**

**First, let me congratulate you on the wonderful HACS application you have created. You have really created something very beautiful. Thank you for the effort you have put into it. So I'm almost annoyed to report that something doesn't seem to be going quite right. Then again, maybe it's just me. 
What's going wrong:
If I add in yaml: shadow: 'yes' a part of the objects disappear. In itself it is not a disaster because then I work without shadow: 'yes' but with this option the lighting is just a bit nicer.
**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:*
![Home Assistant 3D nocolor](https://user-images.githubusercontent.com/59831324/140797608-d92cc854-a9e2-4835-a34a-d9e0a5badba5.png)
![Home Assistant 3D color](https://user-images.githubusercontent.com/59831324/140797623-ef5b38fa-2ead-42b5-9590-8d711ff01948.png)
*

**Comment by adizanni** [comment] 2021-11-08 20:23
Hello Kouwe please refer to the closed issue https://github.com/adizanni/floor3d-card/issues/35.

Please try to open this URL on the browser you use to visualize the card: https://webglreport.com/?v=1

Post the result here below. The parameter called "Max Texture Image Units" is the maximum number of light entities that you can have in your floor3d card when you activate the shadows. Beyond that number the card becomes unstable.
It is not a bug it is simply a limit of your GPU. 

In order to be sure this is the problem, please open the console in your browser and paste here any errors you see when displaying the model with the shadows.

**Comment by Kouwe-sudo** [comment] 2021-11-08 21:32
You were right. I reached the maximum number off lights. 16 in my case. When I removed one everything was back to normal. Excuse me that I didn’t look in the closed issues but a bug is solved or not. I only looked at the open issues. But this turns out not to be a bug but a system limitation. 
We decided to sell the children and move to a smaller house with a maximum of 15 lights to solve the problem. 
Thanks for the quick reply.

**Comment by adizanni** [comment] 2021-11-09 08:47
I sense you are being sarcastic. 

What I can do is to put a control on the number of lights and set a warning when it is going beyond the fixed limit (but I'm not even sure if I can retrieve the limit from some browser object).

Another good evolution could be to put the shadow parameter at light level too, to give the choice about which lights have to cast shadows and which ones don't.

For both I do not consider those as bugs but as new features as they will require some effort to code.

**Comment by Kouwe-sudo** [comment] 2021-11-09 09:44
Sorry, that was absolutely not my intention. I am really very pleased with what you made. It was a joke but apparently not a good one.

**Comment by adizanni** [comment] 2021-11-10 22:21
I've implemented in v1.1.4 the possibility to put 'no' to the shadow parameter of a light for those light we do not want to cast a shadow on. Also now in the console log, the parameter "Max Texture Image Units" is logged at card initialization.

Please validate and close the ticket if you think the bug has been "corrected"

**Comment by adizanni** [comment] 2021-11-14 17:07
As there are no more comments I close the issue, please re-open if you think the fix/workaround is not satisfactory

**Closed by adizanni** 2021-11-14 17:07 UTC
Labels: bug
