### ISSUE TITLE
New Sun setting causes artifacts at top of walls

### ISSUE THREAD

**Issue by reaper7** [adizanni/floor3d-card#83] opened 2022-02-20 11:47 UTC
Hi!

The new SUN setting causes artifacts at top of walls and other elements that reach the height of the room.
This only occurs when the SUN and SHADOW options are enabled.
When the sun is low (near the horizon) or at night then artifacts are not visible.

![art1](https://user-images.githubusercontent.com/4134851/154840928-11c6f7e9-02d3-4261-b8ae-d05d7a27fa8c.jpg)
![art2](https://user-images.githubusercontent.com/4134851/154840932-2c315284-770f-485c-958d-07ab7e6f78ce.jpg)

**Comment by adizanni** [comment] 2022-02-20 14:46
Hello Reaper, have you put a "transparent_slab" in your model ? I have the same behaviour only when putting the transparent_slab on top of the floor. If you have not put that in your model, please send me your model so that I can check why this is happening.

**Comment by reaper7** [comment] 2022-02-20 15:01
yes, I have translucent elements placed there...
like translucent bathroom panel lamps (hidden when turned on) and fragment of a hallway lowered ceiling with spot lamps.

![art](https://user-images.githubusercontent.com/4134851/154848925-1f971374-40ff-4db1-84fd-8b7266b10e96.jpg)

**Comment by adizanni** [comment] 2022-02-20 15:22
I'm looking into it: maybe some iddent property of the the transparent material. As I can reproduce it, I will take care of investigating.

**Comment by adizanni** [comment] 2022-02-27 09:27
hello @reaper7, I've understood the cause of the issue. When the objects have exactly the same elevation, the shadow behaviour is not very well managed. I'm exploring some parameters, but so far when I fix the strange shadow pattern I introduce other side effects. So if it is not bad for your model try to alter slightly the elevation of the transparent objects to make them slightly higher or lower in SH3D (0.5 cm is enough). So far it is the only workaround I can suggest, please let me know

**Comment by reaper7** [comment] 2022-02-28 15:08
Hi @adizanni, I removed all the elements and left only the rooms and the walls
but the artifacts are still there.

![Schowek01](https://user-images.githubusercontent.com/4134851/156006771-b09304ce-f4ca-4f96-b227-71d52706c47f.jpg)

**Comment by adizanni** [comment] 2022-02-28 19:48
Have you verified what is the color that is set for the top of the wall in SweetHome3d ? You can try to set it to white instead of default. Patterns appears only on some walls......

**Comment by reaper7** [comment] 2022-03-13 18:13
on a simple model with white top artifacts are almost invisible
![simple1](https://user-images.githubusercontent.com/4134851/158072895-3be0f9c6-d8d6-4c10-8d4f-16f3891b2dfe.jpg)

but on my model (only with walls) they are still visible
![simple2](https://user-images.githubusercontent.com/4134851/158072942-c9b6531e-3fad-49ce-8c9e-4f862b5b14c8.jpg)

the strange thing is that the artifacts cause the items below, like windows 
![simple3](https://user-images.githubusercontent.com/4134851/158072994-a44a90cd-f293-48c0-8d89-7a67b511931f.jpg)

second, strange thing, why the shadow of the sun looks like stairs? it shouldn't be more like a straight line ? maybe this is causing these weird stripes on top of the walls? 
![simple5](https://user-images.githubusercontent.com/4134851/158073165-d55cf438-2d3c-4b8d-b891-1fbb469021ee.jpg)

![simple4](https://user-images.githubusercontent.com/4134851/158073253-b2518622-10cc-466c-96d6-644c2213c05d.jpg)

**Comment by adizanni** [comment] 2022-03-14 07:40
Yes @reaper7, the shadow generated by the sun is not defined well (low resolution) because it is requiring a lot of calculation. And I also think that it is causing the patterns on the wall. I will check if I can improve

**Comment by reaper7** [comment] 2022-03-14 08:40
@adizanni - relax :) it's a nice addition but I temporarily turned it off, the graphic system is at the limit :)

**Comment by adizanni** [comment] 2022-03-14 10:08
I have created the possibility to put what I call "transparent slab". If you put an invisible object on the ceiling of your floor light is blocked. Condition for it to work:

1. the objects should be named transparent_slab* (meaning you can have more than one but the name of all of them should begin with transparent_slab.
2. you have to use the ExportToHass plugin in order for it to work 

Unfortunately, even when you cover the full model with a transparent slab, the pattern appear.....

**Comment by reaper7** [comment] 2022-03-14 10:33
is it possible to add a exclusion group where there will be elements 
on which we do not want shadows to be generated ? (tops of the walls are separate elements)

**Comment by adizanni** [comment] 2022-03-14 19:40
Yes you are right the wall top is always named the same way so I could exclude it from receiving shadow. I will study a way to make this working in all scenarios (the one you propose seems good). In the meantime please have a look to the v1.3.9 (I'm releasing it right now) with a soft shadow effect.

**Comment by adizanni** [comment] 2022-03-14 19:52
In the new version I have also allowed the ceiling. When Ceiling are dispIayed in Sweethome3d, they turn into transparent shields for the sun (no light pass through them). Activating this feature I realized that the patterns are only appearing on top of the wall when there is a hole or a door underneath.

**Comment by reaper7** [comment] 2022-03-15 16:44
@adizanni - 1.3.9 is better for me, artifacts are much less visible.
It is no longer a chessboard with high contrast and transitions are softer.
![simple_new1](https://user-images.githubusercontent.com/4134851/158428589-5d52c248-9597-4ffc-acf0-9b4c04dba419.jpg)

![simple_new2](https://user-images.githubusercontent.com/4134851/158428600-75cf12f5-477e-4c15-ac54-25f693c7e5a0.jpg)

**Comment by adizanni** [comment] 2022-03-15 17:17
Have you tried to use the ceiling in SweetHome3d (it seems yes from the pictures) ? 
I think that it will be difficult for me to achieve better, but I can keep this issue open for continuous improvement and other cases that may be discovered by users.

**Comment by reaper7** [comment] 2022-03-15 18:40
To be honest I don't know where the ceiling settings are in sh3d, I searched yesterday but couldn't find it.

I think it's ok. Maybe new ideas will emerge over time :)

**Comment by adizanni** [comment] 2022-03-15 19:18
The ceiling parameter is in the room properties dialog (double click on the room)

![image](https://user-images.githubusercontent.com/35622920/158454556-186aa316-ff30-4a73-b21e-2e734278c7df.png)

**Comment by reaper7** [comment] 2022-03-15 20:26
indeed, I have a ceiling in each room, color White and Matt

**Comment by adizanni** [comment] 2022-03-16 19:48
So this is what I saw. Good

**Comment by adizanni** [comment] 2022-03-18 17:57
@reaper7 can you state if we can close the issue ?

**Closed** 2022-03-18 17:59 UTC
Labels: bug
