### ISSUE TITLE
Render is Blank

### ISSUE THREAD

**Issue by Sinfonia97** [adizanni/floor3d-card#31] opened 2021-07-31 20:40 UTC
First of all, thank you for all of the work you have put into this customization.  

I am having a problem with a large complex multi floor model created in sweethome3d.  When I place the new floor3d card into a panel, all that renders is a grey screen.  I've attempted renaming the files thinking it had something to do with spaces, but that did not fix the issue.  My guess is the problem is because of multiple floors, but I can't be for certain.

**Comment by adizanni** [comment] 2021-08-01 07:17
Hello Sinfonia, I have never tried to work with several floor, I may need to do some test from my side. If you can, please send your sh3d file. If not, try to split your model into different individual floor and see if each floor can be rendered in the card.

**Comment by adizanni** [comment] 2021-08-04 20:31
I've tested a simple model with mutli floor and it is working. Maybe, in your case it is that the model is too heavy. It would help to send the sh3d file (as mentioned earlier) and capture the console log from the browser to see if errors are raised.

**Comment by adizanni** [comment] 2021-08-06 13:26
Hello Sinfonia, please post either the card config or sh3d model. If no news before next Wednesday I will close the issue as I cannot reproduce it.

**Closed** 2021-08-13 01:18 UTC
