### ISSUE TITLE
Not Rendering 3D models

### ISSUE THREAD

**Issue by Umarkhabiliy** [adizanni/floor3d-card#72] opened 2022-01-10 06:48 UTC
<a href="https://ibb.co/brrgHjZ"><img src="https://i.ibb.co/4jjZswG/config.png" alt="config" border="0"></a>
<a href="https://ibb.co/74VYnvX"><img src="https://i.ibb.co/jRG6yhT/www.png" alt="www" border="0"></a>
<a href="https://ibb.co/98t4SNx"><img src="https://i.ibb.co/smH1z2T/plan3.png" alt="plan3" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/44DsDZW/community.png" alt="community" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/jGCY3rn/floor.png" alt="floor" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/ck1N19C/js.png" alt="js" border="0"></a>
<a href="https://ibb.co/FhQYFNv"><img src="https://i.ibb.co/x2ngNPv/card.png" alt="card" border="0"></a>

I can tried but not rendered. What is the problem?

**Comment by adizanni** [comment] 2022-01-10 07:04
Hello @Umarkhabiliy, thanks to open the issue separately. Where is the Plan3 folder ?
What do you see in the browser console ? (in chrome, open the menu "More Tools\Developer Tools" and click on the console tab. Cut and paste your log (if you see errors). 
Does your model contains several levels or objects groups created in Sweethome3d ? If you can share somewhere the model (obj or sh3d) it can help me. Thanks

**Comment by Umarkhabiliy** [comment] 2022-01-10 07:13
Ok. I share you, do you have telegram messenger?

**Comment by Umarkhabiliy** [comment] 2022-01-10 07:14
plan3 folder in  www folder

**Comment by Umarkhabiliy** [comment] 2022-01-10 07:21
<a href="https://ibb.co/k0W8jNL"><img src="https://i.ibb.co/J2M7VDY/error.png" alt="error" border="0"></a>

**Comment by Umarkhabiliy** [comment] 2022-01-10 08:49
<a href="https://ibb.co/BNMjkzh"><img src="https://i.ibb.co/zJvbdn3/log.png" alt="log" border="0"></a>
<a href="https://ibb.co/yNKGSMR"><img src="https://i.ibb.co/nw4ZCV0/ert.png" alt="ert" border="0"></a>

**Comment by adizanni** [comment] 2022-01-10 09:02
The most important issue is the first one, it cannot load the floor3dcard.js module, so it is possible you are using an old version in cache. Try to clear your browser history, are you able to load other HACS custom cards ?, Second you receive the error "path is empty" but you showed your config, the path seems correct. It is definetly not a problem with the model, so it is useless to share it with me right now.

**Comment by adizanni** [comment] 2022-01-10 09:12
Please report also at the very beginning of the console log you have the version of the HA custom cards, please confirm that you have v1.1.11 (or tell me which version you have)

**Comment by Umarkhabiliy** [comment] 2022-01-10 09:30
I cleaned cache but nothing change, how check my version ?

**Comment by Umarkhabiliy** [comment] 2022-01-10 09:37
my version is v1.1.11

**Comment by adizanni** [comment] 2022-01-10 09:42
I've seen this forum: https://community.home-assistant.io/t/all-my-custom-cards-suddenly-dont-exist/144135
It is possible that your HACS is broken, are there any other custome cards deployed in HACS that are working fine ?

**Comment by adizanni** [comment] 2022-01-10 10:23
Have you tried to follow the other way to install the floor3d-card? First uninstall the card in HACS then follow my tutorial here https://youtu.be/i3XQVbus4tI to install manually. This is to be sure that you do not have a problem in HACS

**Comment by Umarkhabiliy** [comment] 2022-01-10 13:54
I reinstalled HACS. I added other custom cards, nothing error, but floor3D don’t work.🤯

**Comment by Umarkhabiliy** [comment] 2022-01-10 14:16
<a href="https://imgbb.com/"><img src="https://i.ibb.co/MMr8mhq/noth.png" alt="noth" border="0"></a>

**Comment by adizanni** [comment] 2022-01-10 16:22
I'm really sorry but I cannot find the root cause. Can you post the full configuration of the card by cutting and pasting the code in "show code editor" ? I receive the same error when the path field is actually empty. But it is not your case it seems to be well configured. Also the second error is not fired in the case I do not put the path.......

**Comment by Umarkhabiliy** [comment] 2022-01-10 16:38
I think my problem is "path or navigation" becasuse when i press card i recieve error 
<a href="https://ibb.co/M1np2Kn"><img src="https://i.ibb.co/5jTvMCT/deepin-screen-recorder-google-chro/me-20220110213552.gif" alt="deepin-screen-recorder-google-chrome-20220110213552" border="0"></a>

<a href="https://ibb.co/Wpbd2sg"><img src="https://i.ibb.co/3YD8CkB/jij.png" alt="jij" border="0"></a>
<a href="https://ibb.co/7Q7XKgf"><img src="https://i.ibb.co/HCmVqNS/ll.png" alt="ll" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>перевод с английского на русский с фото</a><br />

**Comment by adizanni** [comment] 2022-01-10 16:45
At the beginning the Path is empty error is normal.

**Comment by Umarkhabiliy** [comment] 2022-01-10 16:52
When i press refresh buttun i recive TypeError: "cannot read properties of undefined(reading 'removeEventListener')

**Comment by Umarkhabiliy** [comment] 2022-01-10 16:54
I cant solve this problem from 2days

**Comment by adizanni** [comment] 2022-01-10 16:56
I'm really sorry, I have never seen something like that.  What happens after you put the right parameters and you save ?

**Comment by Umarkhabiliy** [comment] 2022-01-10 16:59
only this card showed

**Comment by adizanni** [comment] 2022-01-10 16:59
And now what is the error in the console ?

**Comment by adizanni** [comment] 2022-01-10 17:00
It cannot be path is empty, should be something different

**Comment by Umarkhabiliy** [comment] 2022-01-10 17:04
<a href="https://gifyu.com/image/Sbp0w"><img src="https://s10.gifyu.com/images/deepin-screen-recorder_Select-area_20220110220335.gif" alt="deepin-screen-recorder_Select-area_20220110220335.gif" border="0" /></a>

I recieve this error

**Comment by adizanni** [comment] 2022-01-10 17:08
The zIndex is a known bug but it does not stop the model to be displayed. Close your browser and reopen it and refresh the view with the card and tell me if you see this log:

![image](https://user-images.githubusercontent.com/35622920/148807974-65ac6161-dfa5-4915-ac27-ea40e8f0be26.png)

**Comment by Umarkhabiliy** [comment] 2022-01-10 17:09
but after percent is loading to 100,  card is worked but error counting increses i dont know it is nice  or what
 <a href="https://gifyu.com/image/Sbp07"><img src="https://s10.gifyu.com/images/deepin-screen-recorder_Select-area_20220110220601.gif" alt="deepin-screen-recorder_Select-area_20220110220601.gif" border="0" /></a>

**Comment by Umarkhabiliy** [comment] 2022-01-10 17:12
Thank you for your helps brother i wish you all the best

**Comment by Umarkhabiliy** [comment] 2022-01-10 17:30
Everything is good, but  i have another question how i turn on and turn off without other buttons for example if press to the lamp, lamp switch off and switch on

**Comment by adizanni** [comment] 2022-01-10 17:41
You double click on the light object in the model

**Comment by Umarkhabiliy** [comment] 2022-01-10 18:04
I double click object but nothing change

**Comment by adizanni** [comment] 2022-01-10 18:42
Have you configured your light in the card ?

**Comment by Umarkhabiliy** [comment] 2022-01-10 19:04
<a href="https://imgbb.com/"><img src="https://i.ibb.co/fF5HrpC/h.png" alt="h" border="0"></a>
<a href="https://ibb.co/ChMzX7Y"><img src="https://i.ibb.co/86d0R5f/67.png" alt="67" border="0"></a>

it is enough?

**Comment by adizanni** [comment] 2022-01-10 19:18
Also remove the entity template value it is useless in this context. Are you sure that your switch is called that way ?

**Comment by Umarkhabiliy** [comment] 2022-01-10 19:38
lumens 1000, yeah my devices name switch...  when i press  toggle, lamp light, however double clicked to the object nothing off or on

**Comment by adizanni** [comment] 2022-01-10 20:57
The name of the light object in the model is weird. If you say that now you see the light in the model, it means that the object is working, on the other hand, if the light is getting our from the object, it means that if you double click it should work. Send me the full configuration (not an image but the full text of your config)......

**Comment by adizanni** [comment] 2022-01-11 09:38
Please close the issue and open new one if you see that the card is not working as expected

**Comment by Umarkhabiliy** [comment] 2022-01-11 14:10
<a href="https://ibb.co/q9Ympmk"><img src="https://i.ibb.co/d64kDkG/nm.png" alt="nm" border="0"></a>/
it is Confugration

**Comment by Umarkhabiliy** [comment] 2022-01-11 16:53
Yes I’m tried give big object however doesn’t work. Can you give more information about confugration, may be I don’t understand clearly, can you make a video to youtube

**Comment by Umarkhabiliy** [comment] 2022-01-12 09:35
is it true?

**Closed** 2022-01-13 17:50 UTC
Labels: bug
